### PR TITLE
sci-biology/fsl: credit and detail the patches.

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: Portage-2.3.79, Repoman-2.3.16

### CODE REVIEW

**Comment by kiwifb** [comment]
Forgot I had to rebase on your repo. Will you be OK or should I rebase?

**Comment by TheChymera** [comment]
@kiwifb please rebase, this sort of thing always blows up in my face :-/

**Comment by kiwifb** [comment]
Done. Sorry for the delay.

**Comment by kiwifb** [comment]
Ping. This is ready to merge.

**Comment by TheChymera** [comment]
@kiwifb sorry for the delay.

**Pull request merged**
